name: CI

on:
  workflow_dispatch:

jobs:
  launch-microshift:
    runs-on: ubuntu-20.04
    steps:
      - name: Set hostname
        run: |
          # The host needs a fqdn domain for MicroShift to work well
          sudo hostnamectl set-hostname cluster.cryostat.io
      - uses: actions/checkout@v3
        with:
          repository: tthvo/microshift_ci
      - uses: actions/setup-go@v4
        with:
          go-version: '1.15.2'
      - name: Build MicroShift for AMD64
        run: sudo bash .github/build_microshift.sh
      - name: Enable MicroShift
        run: sudo bash .github/install_microshift.sh
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: "^4"
      - name: Check if microshift is running
        run: |
          oc config view
          oc cluster-info
          oc whoami
          oc get pods -A

